# Sample Code:
# print(event.get('task_string_key'))
# event.set('task_int_array_key', [456, 789]);
# event.log('some logging')

from google.cloud import datastore

def create_entity(client, kind, payload, entity_id=None, exclude_from_indexes=[]):
  if entity_id:
      # Custom key
      key = client.key(kind, entity_id)
  else:
      # Autogenerated key
      key = client.key(kind)

  entity = datastore.Entity(
      key=key,
      exclude_from_indexes=exclude_from_indexes,
  )
  entity.update(payload)

  return entity

def run(event):

  kind = event.get('kind')
  payload = event.get('payload')
  entity_id = None

  try:
    entity_id = event.get('entity_id')
  except:
    print("No entity_id provided")

  if kind == None:
    raise "WTF: where is the kind?"

  if payload == None:
    raise "WTF: where is the payload?"  

  print("kind", kind)
  print("payload", payload)
  
  client = datastore.Client()
  entity = create_entity(client, kind, payload, entity_id)
  
  client.put(entity)

  return
